import { dirs } from '../shared-vars';

//This file controls what goes into the index.pug files that are generated into the pages folder
//if editing this, keep in mind that this affects every page on the site, including the home page

export default function (pageMap, index, parent, contentExists) {
	var contentInclude = contentExists ? 'include _content' : '';
	//const siteContent = require('../../../'+dirs.temporary+'/content.json');
	//const content = typeof siteContent[pageMap.id] !== 'undefined'  ? siteContent[pageMap.id].content : [];

	return `
//- This file is generated using gulp. DO NOT EDIT THIS FILE!
//- source file can be found in the gulp config generator template "page_pug_file.js"

extend /_4_templates/${pageMap.template}

block append pre_nav_config
	- var location = [${pageMap.location}];

${contentInclude}
`;
	//${readContent(content, 0)}
}

// function readContent(contentArray, tabDepth){

// 	const t = '\t'.repeat(tabDepth);

// 	let returnVal = '';

// 	contentArray.forEach((tag, index)=>{

// 		const attributes = JSON.stringify(tag.attributes);

// 		const content = Array.isArray(tag.content) ? readContent(tag.content, ++tabDepth) : tag.content;

// 		const pugSnippets = {
// 			intro : `
// ${t}block ${tag.name}
// ${t}	${content}`,
// 			body : `

// ${t}block ${tag.name}` + content,
// 			content : `
// ${t}+cmsContent(${attributes})
// ${t}	${content}`,
// 			img : `
// ${t}img(src='assets/${tag.attributes.src}', alt='${tag.attributes.alt}')`,
// 			quote : `
// ${t}+blockquote(${attributes})
// ${t}	${content}`,
// 			video : `
// ${t}+videoPlayer(${attributes})`,
// 		}

// 		returnVal = returnVal + pugSnippets[tag.name];

// 	});

// 	return returnVal;
// };
